### ISSUE TITLE
Removing blocked phrases is too aggressive

### ISSUE THREAD

**Issue by Caseysch** [jessey-git/yammerblock#5]
If a comment contains a blocked phrase, the entire comment thread is hidden (one parent too many?) Might apply to blocked users as well, haven't tested.

Will look at later.

**Comment by Caseysch** [comment]
Also not aggressive enough, as you can't block based on a link.

**Comment by jessey-git** [comment]
Yeah, looks like it ends up selecting the <ul> list of all messages to hide I think.  A change to $posts.parents().eq(3) instead of 4 seems ok at first glance.

**Comment by jessey-git** [comment]
Could you try with the changes I just pushed? Reactivate if necessary

**Comment by Caseysch** [comment]
Verified that it leaves the other comments alone now, thanks!
