### ISSUE TITLE
Manifest is invalid for W10 Anniversary Update

### ISSUE THREAD

**Issue by atiensivu** [jessey-git/yammerblock#6]
It is missing the 'author' field and the "20"/"40" for icons. 
I hacked up the manifest and it seems to load now but I'm not an extensions wizard. 

{
    "manifest_version": 2,

    "name": "Yammer Block",
    "author": "Microsoft Corporation",
	"description": "Blocks crappy yammer junk",
    "version": "1.0",

    "icons": {
        "48": "content/images/icon-48.png",
        "128": "content/images/icon-128.png"
    },

    "options_ui": {
        "page": "options.html",
        "chrome_style": true
    },

    "browser_action": {
        "default_icon": 
		{
			"20" : "content/images/icon-19.png", 
			"40" : "content/images/icon-48.png"
		},
        "default_title": "Yammer Block"
    },

    "content_scripts": [
        {
            "matches": ["https://www.yammer.com/microsoft.com/*"],
            "run_at": "document_end",
            "js": ["scripts/jquery-3.0.0.min.js", "scripts/yamblock.js"]
        }
    ],

    "permissions": [
        "activeTab",
        "storage",
        "https://ajax.googleapis.com/"
    ]
}

**Comment by jessey-git** [comment]
Yay that it nearly works in Edge.  Boo that it seems to want some optional manifest elements.  Boo that I apparently used the wrong schema for default_icon anyhow...

atiensivu - How do I load non-Store extensions in Edge to test out fixes?

**Comment by jessey-git** [comment]
Can you try again with the latest changes i just pushed to see if it works now?  Reactivate as necessary
